### ISSUE TITLE
 ERROR    Warning: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by agungs17** [alessiocancian/react-native-side-menu#2]
this error show if i used onchange function to update state, im used hooks component for with this

**Comment by alessiocancian** [comment]
It's not an error but a warning:
https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render

Anyway this shouldn't happen with a proper onChange function, because it doesn't get called on the first render, but only when menu is opened or closed...
What are you passing to onChange prop?
